### ISSUE TITLE
The demo image in the readme is broken

### ISSUE THREAD

**Issue by choldgraf** [pradyunsg/lutra#13]
This image is broken:

https://github.com/pradyunsg/lutra/blob/957b3961a5a3cc4a3bacca5f67bb6c06e7c9eb2b/README.md?plain=1#L3-L5

**Comment by pradyunsg** [comment]
Yup. I’ll add it once the image things once the site design is settled enough to not change drastically. :)

**Comment by pradyunsg** [comment]
I appreciate you flagging this! ^.^
