### ISSUE TITLE
Version selector not yet showing on readthedocs?

### ISSUE THREAD

**Issue by johanneskoester** [pradyunsg/lutra#61]
This is an awesome theme, thanks a lot! Can you comment on the version selector support? It seems like it is implemented, but when rendering on readthedocs, it is not displayed currently.

**Comment by ftabaro** [comment]
Hi Johannes! Indeed, no selector is available from the current version of the docs. As a temporary workaround, older versions of the Snakemake documentation can be found here:

https://readthedocs.org/projects/snakemake/

**Comment by pradyunsg** [comment]
This theme is not ready for reuse yet, please don't try using it for now.

**Comment by johanneskoester** [comment]
It works pretty well for our use case, and I am happy to contribute fixes. It is also fine if you just give me a pointer and I will try to fix it myself.

**Comment by johanneskoester** [comment]
Well, I have found an alternative theme that works as well and is similar in terms of the optical properties (sphinxawesome-theme). We will use that for now. Nevertheless congrats for the great work here and I will keep an eye on it for maybe switching to it in the future!
