### ISSUE TITLE
Don't link to Sphinx theme via Github icon in footer

### ISSUE THREAD

**Issue by corneliusroemer** [pradyunsg/lutra#63]
The theme is nice, I came across it as snakemake uses it for their docs.

One thing that I find jarring though is that the Github icon in the footer points at the sphinx theme github repo rather than at the repo of the software being documented. The theme is already linked from the text in the bottom left of the footer. That should be enough. The Github icon should link to the project and not the theme.

<img width="2250" alt="image" src="https://github.com/pradyunsg/lutra/assets/25161793/ea35fa31-9702-458c-bc2c-21406c149417">

See https://github.com/snakemake/snakemake/issues/2621

Related to: https://github.com/pradyunsg/lutra/issues/37

**Comment by pradyunsg** [comment]
This theme is not ready for reuse yet, please don't try using it for now.
