### ISSUE TITLE
Link in README goes 404

### ISSUE THREAD

**Issue by corneliusroemer** [pradyunsg/lutra#64]
This README link goes 404:

<img width="751" alt="image" src="https://github.com/pradyunsg/lutra/assets/25161793/eb3d3618-4e18-4755-8a14-417555d264f3">

https://pradyunsg.me/lutra/quickstart

**Comment by pradyunsg** [comment]
This theme is not ready for reuse yet, please don't try using it for now.

**Comment by corneliusroemer** [comment]
Thanks for the response! Maybe you could make this clear in the README 

By the way you could add "snakemake" to "used by" in the README :D
